### PR TITLE
Update Year 63 - Defrag Disordered (speed).txt

### PR DESCRIPTION
**Pull request by n05ucc4u**
in collaboration with commonnickname

### CODE REVIEW

**Comment by hingston** [comment]
I'm getting the error:
`You can't paste that here! It uses features that are not available in this room.`

**Comment by n05ucc4u** [comment]
Weird, it works for me. Please try to paste it again.

**Comment by NeunEinser** [comment]
Can confirm this solution, pasting does work for me as well and completes in 5 seconds

**Comment by hingston** [comment]
Oops my mistake, must have copy something extra at the end.

**Pull request merged**
