### PR TITLE
Year 60 - 11 commands (50+) / 9 commands (low)

### PR DESCRIPTION
**Pull request by NeunEinser**
This level is beatable with a 11 command solution. Technically, it should never fail, but sometimes it takes too long and the game gives up on it.
The 9 command solution is basically the same, just with 2 ifs less. Like that, the solution is generally going to take too long for completing, but running it a few times, it will actually complete. It doesn't count towards the 50% treshhold though, and it is not close to that at all.

### CODE REVIEW

**Comment by NeunEinser** [comment]
I am actually not sure what the rules for <50% are. If theoretical solutions that can be proven to work in one instance, you could just assume an already sorted row here which would make this solution trivial. But that is true for most puzzles. If you assumne some extremly rare conditions, you can make stuff happen way faster than it will ever complete in game.
Ofc, this category might be more interesting if it only allows solutions that will work in maybe 1%+ or something similar, so that you can actually see them working in action.
So depending on the rules, I might want to remove the low% file from the commit, since a low% solution might be trivial for this level.

**Comment by n05ucc4u** [comment]
yeah, thought about that too (i asked to create this category, because wanted to share some interesting solutions, like local maximums in 4i, which passed the 25 tests check in a bit less than 50% of the cases).

**Comment by n05ucc4u** [comment]
there is already a 99%+ 10i understaffed sorting solution btw.

**Comment by NeunEinser** [comment]
Ah, I think this one got merged after I posted this. Anyways, I did not see that solution back then.

**Pull request closed without merging**
