### PR TITLE
Update Year 22 23 42 48 59 63 66 67

### PR DESCRIPTION
**Pull request by eiTTio**
fixed

### CODE REVIEW

**Comment by commonnickname** [comment]
I ran your 42 solution to 10 times (250 tries) and got 6 fails in total, which gives a success rate of about 97,6%. Not sure whether testing it more times would make it 99%+.

**Comment by eiTTio** [comment]
> 
> 
> I ran your 42 solution to 10 times (250 tries) and got 6 fails in total, which gives a success rate of about 97,6%. Not sure whether testing it more times would make it 99%+.

ok，got improved version, no falls

**Comment by hingston** [comment]
I'm half way through. I'll need a little more time to test all these :)

**Comment by hingston** [comment]
@eiTTio nice work! In future could you make individual pulls for each year, it would make it a lot easier to track my testing and comment on each individually if necessary.

I can't get 63 to pass 50%.

**Pull request merged**
