### PR TITLE
Create Year 39 - Printing Etiquette 1 (size).txt

### PR DESCRIPTION
**Pull request by n05ucc4u**
6i

### CODE REVIEW

**Comment by hingston** [comment]
This seems to be passing 99% for me?

**Comment by n05ucc4u** [comment]
It certainly isn't 99%+, try to run it again, you'll probably see a few red bars on the success screen (or it won't pass).

**Comment by hingston** [comment]
Wow, I must have been incredibly lucky. I ran it 5 times and only saw 1 fail yesterday.

**Comment by hingston** [comment]
Sorry for the very delayed response!

**Pull request merged**
