### PR TITLE
Reduce year 32 size count by removing if operation

### PR DESCRIPTION
**Pull request by kalokng**

### CODE REVIEW

**Comment by n05ucc4u** [comment]
That would make it not 100%.

**Comment by lukeng** [comment]
The old solution is not 99+ also.
Or should I move the file to 50+?

**Comment by n05ucc4u** [comment]
> The old solution is not 99+ also.
I tried running old solution a few times and it didn't fail once, although maybe I got lucky. 
> Or should I move the file to 50+?
Yes, do that.

**Comment by kalokng** [comment]
There is another solution with same steps in 50+, so I will just close this PR.

**Pull request closed without merging**
