### PR TITLE
Create Year 58 - Good Neighbors (size speed good ratio)

### PR DESCRIPTION
**Pull request by Blanvillain**
The actual 3 sec speed proposal doesn't really solve the challenge: it makes exploding blocks and is quite long (108 lines). This solution is shorter (24 lines) and can still do the job in 14 sec. Thus it might be interesting to archive this algorithm with good speed/size ratio.

### CODE REVIEW

**Comment by hingston** [comment]
Good solution! But I'm not sure if it can be included. The current objective is to achieve speeds the same as or better than on the OCD+ page. Until the game is patched the 3 second solution completes the level faster.

**Comment by main-gi** [comment]
Would be cool to keep around regardless if you're making graphs.

**Comment by Blanvillain** [comment]
We could create a third folder called "SolutionsAlt" to keep alternative solutions like this one?

**Comment by hingston** [comment]
@Blanvillain Could you set that up?

**Pull request closed without merging**
