### PR TITLE
Y 10 size; Y 13 size; Y 12 size, speed; Y 41 speed; Y 44 size; Y 49 both; Y 50 size, speed; Y 51 speed; Y 59 size; Y 66 speed; Y 67 speed

### PR DESCRIPTION
**Pull request by commonnickname**
Solutions to year 12: size 7i; speed 3s.

### CODE REVIEW

**Comment by commonnickname** [comment]
All 100% except year 44, which is rng-based and theoretically could time out, but I haven't seen it happen

**Comment by hingston** [comment]
Nice work! I'll check over them tomorrow

**Comment by commonnickname** [comment]
Just added Year 12 7i >50% and Year 10 5i >99%. I suspect those might get patched, but it works for now

**Comment by hingston** [comment]
All look good! Could you please follow the current naming convention though. Then I'll merge it.

###### File Naming Rule

Year `NUM` - `NAME` (`TYPE`).txt

`NUM` = 02-68

`NAME` = The name puzzle's name

`TYPE` = Speed, Size or Both

**Comment by commonnickname** [comment]
Done. Unfortunately I couldn't get the trailing plus to work with folder names, so I reuploaded Year 12 speed and Year 49 into the right folders instead.

**Comment by commonnickname** [comment]
Added two more solutions: Year 66 speed (26s) and Year 67 speed (47s)

**Pull request merged**
