### PR TITLE
Multiplication Table 10i 49s, Identify Yourselves 6i, Decimal Doubler instructions improvement

### PR DESCRIPTION
**Pull request by main-gi**

### CODE REVIEW

**Comment by main-gi** [comment]
* Decimal Doubler's instructions improvement is on the speed score. The speed has not been improved but it is more compact now

**Comment by hingston** [comment]
Could you provide the 22i solution to year 62? It would beat the best known solution for size.

**Comment by main-gi** [comment]
Honestly I wasn't planning to. Because there's already a known better one, 20i, and I wanted a chance at the record. But I think this solution isn't going to give it, so:

-- 7 Billion Humans (2056) --
-- 62: The Sorting Floor --

comment 0
if e == hole and
 s == hole:
	a:
	mem1 = foreachdir nw,w,sw,n,s,ne,e,se:
		drop
	endfor
	tell everyone go
	jump a
endif
mem4 = foreachdir s,e,se:
	step n
endfor
b:
mem2 = foreachdir w,n,s,e:
	step mem2
	if c > e or
	 e > sw and
	 e == worker:
		if e > sw:
			pickup sw
		endif
		pickup c
		giveto e
		pickup e
		if sw == nothing and
		 s >= 0:
			step sw
			drop
			step ne
		endif
	endif
	listenfor go
	drop
endfor
jump b


DEFINE COMMENT 0
eJztkM9LVGEUhp+9FCoiI4gMKi7UREIkVAx0F2XgooULFxFBaqLDJDd16EURBmw2EtEPjXExgtbKVmku
dCG4qY26UBhHkFahJaRb36vzV0gHHr5z73fOe97zJXEU0KCb1KiISpWaCNUqp55yWlRGF8XEfC/dQBT6
rCAgSpxKU0UslKCOCt0iwm1XN5sW523UqpVm3eERTQyokcB54Lu42s1d63YyFLari27zWA99H8YDTwjj
rdU+UMtHa81Sw7zJ2G/Gihk6lHbPHAO8t69PJs24FqyxaJY847P5kve4TL2+er9v9rZm1olqg0Y2vOd3
elmlzww5j2ndbFk39PaTiHZcv08JByZHqQ7dm/NuB7Qpy32y+dpT/zumnWM6OOGe/vr9zujRuX2e+w3+
WffUnv7Y3++rXRV4ZtwMMqJ+xu1CPGVGT0ibZeebPGOb52Q1zJFe8IuEmSSnKfaUZFfT/CDFplKs+Hx3
qTtp/Qm/uTzvlUn4rcfMS88JGDVJf29f1qZ4kz9n3P/amhPuH+V/XPu4ABSSlZE;

**Comment by main-gi** [comment]
By the way, here is a picture of the better 20i solution. Note that whoever solved it didn't give the solution. https://steamcommunity.com/app/792100/discussions/0/1732087824984042131/

**Pull request merged**
